Spring:
    host: localhost/8080
    basepath: /api
    scheme:
      -http
      -https
    datasource:
      platform: h2
      url: "jdbc:h2:mem:testdb"
      console:
        enabled: true
        path: "/h2"
      username: test
      password: test
      driverClassName: org.h2.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
          hibernate:
            format_sql: true




