spring:
  application:
    name: enterprise-banking-api

  datasource:
    url: jdbc:postgresql://localhost:5432/Bank_ProjectDB
    username: ${DB_USERNAME:banking_user}
    password: ${DB_PASSWORD:banking_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        generate_statistics: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  security:
    headers:
      content-security-policy: "default-src 'self'"
      frame-options: DENY
      content-type-options: nosniff
      xss-protection: 1; mode=block

  transaction:
    default-timeout: 30
    rollback-on-commit-failure: true

server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
  http2:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.enterprise.banking: INFO
    org.springframework.transaction: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"
  file:
    name: logs/banking-api.log

banking:
  security:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      max-age: 3600

  transaction:
    daily-limit: 10000
    minimum-deposit: 1
    minimum-withdrawal: 1

  audit:
    enabled: true
    retention-days: 2555  # 7 years



